create_speed_test_module
softwareNPI/speed_test pull request #1
Opened 2023-05-03 13:07 UTC by ibrahim-zebary

2023-05-03 14:09 UTC, Al-Taie requested changes

2023-05-03 14:09 UTC, Al-Taie commented on speedtest/src/main/java/com/gateway/speedtest/SpeedTest.kt
> +        fileSize: Int = 100000000,
for readability, I suggest using underscore with the large numbers **`100_000_000`**

2023-05-03 14:09 UTC, Al-Taie commented on speedtest/src/main/java/com/gateway/speedtest/entity/MSpeedTestReport.kt
> +data class MSpeedTestReport(
rename this class to **`SpeedTestReport`**

2023-05-03 14:09 UTC, Al-Taie commented on speedtest/src/main/java/com/gateway/speedtest/SpeedTestListener.kt
> +    private fun processSpeedTestReport(report: SpeedTestReport, startTime: Long): MSpeedTestReport {
to avoid conflict with names you can use **`as`** operator to rename the class while importing it
```kotlin
import com.gateway.speedtest.entity.SpeedTestReport
import fr.bmartel.speedtest.SpeedTestReport as LibSpeedTestReport

fun processSpeedTestReport(report: LibSpeedTestReport , startTime: Long): SpeedTestReport)
```
or you can use full path with when using it
```kotlin
fun processSpeedTestReport(report: fr.bmartel.speedtest.SpeedTestReport , startTime: Long): SpeedTestReport)
```

but I suggest the first option for readability.

2023-05-03 14:09 UTC, Al-Taie commented on speedtest/src/main/java/com/gateway/speedtest/entity/extensions.kt
> +internal fun Long.bitToMb() = this / 125000.0
put the **extensions files** in **`utils`** package.

2023-05-03 14:09 UTC, Al-Taie commented on speedtest/src/main/java/com/gateway/speedtest/entity/MSpeedTestReport.kt
> +sealed class SpeedTestState {
move **`SpeedTestState`** class to separated file.

2023-05-07 09:04 UTC, ibrahim-zebary commented on speedtest/src/main/java/com/gateway/speedtest/entity/MSpeedTestReport.kt
> +data class MSpeedTestReport(
The library that we use to measure the speed test is SpeedTestReport

2023-05-07 12:14 UTC, Al-Taie approved these changes

2023-05-07 12:14 UTC, merged